<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Programma_test" Id="{986bfd2d-1d24-4789-aa62-0d912b886579}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Programma_test
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Programma_test">
      <LineId Id="228" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>